import 'dotenv/config'

export const env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  REDIS_URL: process.env.REDIS_URL ?? 'redis://localhost:6379',
  JWT_SECRET: process.env.JWT_SECRET ?? 'dev-secret',
  WHATSAPP_VERIFY_TOKEN: process.env.WHATSAPP_VERIFY_TOKEN ?? 'dev-whatsapp-verify-token',
  WHATSAPP_PROVIDER: process.env.WHATSAPP_PROVIDER ?? 'webhook',
  WHATSAPP_OUTBOUND_WEBHOOK_URL: process.env.WHATSAPP_OUTBOUND_WEBHOOK_URL,
  WHATSAPP_OUTBOUND_WEBHOOK_TOKEN: process.env.WHATSAPP_OUTBOUND_WEBHOOK_TOKEN,
  WHATSAPP_ZAPI_SEND_TEXT_URL: process.env.WHATSAPP_ZAPI_SEND_TEXT_URL,
  WHATSAPP_ZAPI_SEND_BUTTON_ACTIONS_URL: process.env.WHATSAPP_ZAPI_SEND_BUTTON_ACTIONS_URL,
  WHATSAPP_ZAPI_SEND_BUTTON_LIST_URL: process.env.WHATSAPP_ZAPI_SEND_BUTTON_LIST_URL,
  WHATSAPP_ZAPI_CLIENT_TOKEN: process.env.WHATSAPP_ZAPI_CLIENT_TOKEN,
  WHATSAPP_CLOUD_API_VERSION: process.env.WHATSAPP_CLOUD_API_VERSION ?? 'v22.0',
  WHATSAPP_CLOUD_PHONE_NUMBER_ID: process.env.WHATSAPP_CLOUD_PHONE_NUMBER_ID,
  WHATSAPP_CLOUD_ACCESS_TOKEN: process.env.WHATSAPP_CLOUD_ACCESS_TOKEN,
  HUB_FRONTEND_URL: process.env.HUB_FRONTEND_URL ?? 'http://localhost:3000',
  PARCEIRO_INTERNO_NOME: process.env.PARCEIRO_INTERNO_NOME ?? 'Viseu Advogados',
  ORQ_D1_HORAS_ANTES: Number(process.env.ORQ_D1_HORAS_ANTES ?? 24),
  ORQ_REITERACAO_HORAS_ANTES: Number(process.env.ORQ_REITERACAO_HORAS_ANTES ?? 6),
  ORQ_SEM_RESPOSTA_MINUTOS_DEPOIS: Number(process.env.ORQ_SEM_RESPOSTA_MINUTOS_DEPOIS ?? 60),
  ORQ_CHECKIN_MINUTOS_ANTES: Number(process.env.ORQ_CHECKIN_MINUTOS_ANTES ?? 60),
  ORQ_POS_MINUTOS_DEPOIS: Number(process.env.ORQ_POS_MINUTOS_DEPOIS ?? 30),
  ORQ_TIMEZONE: process.env.ORQ_TIMEZONE ?? 'America/Sao_Paulo',
  PORT: Number(process.env.PORT ?? 3001),
  HOST: process.env.HOST ?? '0.0.0.0',

  // Resend (e-mail)
  RESEND_API_KEY: process.env.RESEND_API_KEY ?? '',
  EMAIL_FROM: process.env.EMAIL_FROM ?? 'Freedom.AI Hub <onboarding@resend.dev>',
}
